const ROLES = Object.freeze({
  CUSTOMER: 'CUSTOMER',
  SERVICE_PROVIDER: 'SERVICE_PROVIDER',
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  OPERATIONS_MANAGER: 'OPERATIONS_MANAGER',
  SUPPORT_AGENT: 'SUPPORT_AGENT',
});

const ALL_ROLES = Object.values(ROLES);

const STAFF_ROLES = [ROLES.PLATFORM_ADMIN, ROLES.OPERATIONS_MANAGER, ROLES.SUPPORT_AGENT];

const BOOLEAN_STATUS = Object.freeze({
  TRUE: 'true',
  FALSE: 'false',
});

module.exports = { ROLES, ALL_ROLES, STAFF_ROLES, BOOLEAN_STATUS };